### ISSUE TITLE
special character in spotify password causes issues

### ISSUE THREAD

**Issue by king-gizzard** [forslund/spotify-skill#31]
in my case, there was a 'ü' (u'\xfc') in my spotify password, which apparently caused mycroft to spam me with errors as long as spotify was playing. changing the password (not too big a deal) did solve the issue, but i could not fnd any documentation of this so i figured i would share it here.
i have mycroft running in terminal on an archlinux (manjaro) system, please request any additional information if needed.

```
00:53:50.500 - SKILLS - DEBUG - {"data": {"expect_response": false, "utterance": "An error occurred while processing a request in Spotify Skill"}, "type": "speak", "context": {}}
00:53:50.560 - SKILLS - DEBUG - {"data": {"side": "b"}, "type": "enclosure.eyes.blink", "context": null}
00:53:50.566 - SKILLS - DEBUG - {"data": {}, "type": "recognizer_loop:audio_output_start", "context": null}
00:53:54.697 - SKILLS - DEBUG - {"data": {}, "type": "recognizer_loop:audio_output_end", "context": null}
00:53:55.283 - SKILLS - DEBUG - {"data": {}, "type": "3725241627858187020:MonitorSpotify", "context": null}
00:53:55.287 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
00:53:55.473 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/currently-playing HTTP/1.1" 200 1015
00:53:55.486 - mycroft.skills.core:wrapper:609 - ERROR - An error occurred while processing a request in Spotify Skill
Traceback (most recent call last):
  File "/home/USER/mycroft-core/mycroft/skills/core.py", line 601, in wrapper
    self.settings.store()  # Store settings if they've changed
  File "/home/USER/mycroft-core/mycroft/skills/settings.py", line 552, in store
    if self._should_upload_from_change:
  File "/home/USER/mycroft-core/mycroft/skills/settings.py", line 534, in _should_upload_from_change
    if str(remote_val) != str(self_val):
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 7: ordinal not in range(128)
```

**Comment by forslund** [comment]
Hi, can you check if the recent update to python3 has improved this issue?

**Comment by forslund** [comment]
I believe this has been resolved and will close. If you still have issue with this feel free to reopen the issue.
