### ISSUE TITLE
An error has occured

### ISSUE THREAD

**Issue by ezraholm50** [forslund/spotify-skill#35]
Hey great skill thanks!

All commands result in an error has ocurred!
Like:

Hey mycroft, play drake on spotify

Only hey mycroft what devices are available, result in actual output.

Could anyone help me out?

**Comment by forslund** [comment]
Hi! What platform are you on?

Also in this case it would be helpful if you could check the mycroft-skills.log file for the error information. (on picroft/mark-1 in /var/log/mycroft-skills.log on git installations in mycroft-core/scripts/mycroft-skills.log)

**Comment by ezraholm50** [comment]
I'm sorry, should have stated my OS and logs of course. 

OS: Debian/Ubuntu (Deepin OS)

Logs:
cat scripts/logs/mycroft-skills.log | grep spotify
```
16:50:58.460 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
16:50:58.557 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/currently-playing HTTP/1.1" 204 0
16:51:10.381 - git.cmd - DEBUG - Popen(['git', 'config', 'remote.origin.url'], cwd=/opt/mycroft/skills/mycroft-spotify.forslund, universal_newlines=False, shell=None)
16:51:20.856 - mycroft.skills.core:load_skill:105 - INFO - ATTEMPTING TO LOAD SKILL: mycroft-spotify.forslund with ID mycroft-spotify.forslund
16:51:23.466 - SKILLS - DEBUG - {"context": {"ident": "1526482280.98677338774778345797868604", "client_name": "mycroft_listener"}, "data": {"utterances": ["what spotify devices are available"], "session": "c970d1cd-5908-4807-950c-87b2f6c1c45e", "lang": "en-US"}, "type": "recognizer_loop:utterance"}
16:51:23.478 - SKILLS - DEBUG - {"data": {"utterance": "what spotify devices are available", "lang": "en-US"}, "context": {"client_name": "mycroft_listener", "ident": "1526482280.98677338774778345797868604"}, "type": "intent_failure"}
16:51:23.480 - mycroft.skills.padatious_service:handle_fallback:107 - DEBUG - Padatious fallback attempt: what spotify devices are available
16:51:24.217 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundSearch", "start": "search"}, "context": null, "type": "register_vocab"}
16:51:24.221 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundSearch", "start": "look for"}, "context": null, "type": "register_vocab"}
16:51:24.224 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundDevice", "start": "device"}, "context": null, "type": "register_vocab"}
16:51:24.227 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundDevice", "start": "unit"}, "context": null, "type": "register_vocab"}
16:51:24.266 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundDevice", "start": "devices"}, "context": null, "type": "register_vocab"}
16:51:24.267 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundDevice", "start": "units"}, "context": null, "type": "register_vocab"}
16:51:24.267 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundTransfer", "start": "transfer"}, "context": null, "type": "register_vocab"}
16:51:24.268 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundTransfer", "start": "move"}, "context": null, "type": "register_vocab"}
16:51:24.269 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundPlay", "start": "play"}, "context": null, "type": "register_vocab"}
16:51:24.269 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundPlay", "start": "listen to"}, "context": null, "type": "register_vocab"}
16:51:24.271 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundPlay", "start": "start"}, "context": null, "type": "register_vocab"}
16:51:24.271 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundSpotify", "start": "Spotify"}, "context": null, "type": "register_vocab"}
16:51:24.273 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundSpotify", "start": "using Spotify"}, "context": null, "type": "register_vocab"}
16:51:24.274 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundSpotify", "start": "with Spotify"}, "context": null, "type": "register_vocab"}
16:51:24.275 - SKILLS - DEBUG - {"data": {"end": "mycroft_spotify_forslundSpotify", "start": "on Spotify"}, "context": null, "type": "register_vocab"}
16:51:24.276 - SKILLS - DEBUG - {"data": {"regex": "search.*for (?P<mycroft_spotify_forslundSpotifyTitle>.+)"}, "context": null, "type": "register_vocab"}
16:51:24.277 - SKILLS - DEBUG - {"data": {"regex": "search.*for the album (?P<mycroft_spotify_forslundSpotifyTitle>.+)"}, "context": null, "type": "register_vocab"}
16:51:24.279 - SKILLS - DEBUG - {"data": {"regex": "album (?P<mycroft_spotify_forslundAlbumTitle>.+)"}, "context": null, "type": "register_vocab"}
16:51:24.280 - SKILLS - DEBUG - {"data": {"regex": "to (?P<mycroft_spotify_forslundToDevice>.+)"}, "context": null, "type": "register_vocab"}
16:51:24.282 - SKILLS - DEBUG - {"data": {"time": 1526482584.0, "repeat": 300, "data": {}, "event": "mycroft-spotify.forslund:SpotifyLogin"}, "context": null, "type": "mycroft.scheduler.schedule_event"}
16:51:27.740 - SKILLS - DEBUG - {"data": {"file_name": "/opt/mycroft/skills/mycroft-spotify.forslund/vocab/en-us/PlaySomeMusic.intent", "name": "mycroft-spotify.forslund:PlaySomeMusic.intent"}, "context": null, "type": "padatious:register_intent"}
16:51:27.741 - mycroft.skills.padatious_service:_register_object:89 - DEBUG - Registering Padatious intent: mycroft-spotify.forslund:PlaySomeMusic.intent
16:51:27.742 - SKILLS - DEBUG - {"data": {"file_name": "/opt/mycroft/skills/mycroft-spotify.forslund/vocab/en-us/PlayAlbum.intent", "name": "mycroft-spotify.forslund:PlayAlbum.intent"}, "context": null, "type": "padatious:register_intent"}
16:51:27.744 - mycroft.skills.padatious_service:_register_object:89 - DEBUG - Registering Padatious intent: mycroft-spotify.forslund:PlayAlbum.intent
16:51:27.745 - SKILLS - DEBUG - {"data": {"file_name": "/opt/mycroft/skills/mycroft-spotify.forslund/vocab/en-us/PlaySong.intent", "name": "mycroft-spotify.forslund:PlaySong.intent"}, "context": null, "type": "padatious:register_intent"}
16:51:27.747 - SKILLS - DEBUG - {"data": {"file_name": "/opt/mycroft/skills/mycroft-spotify.forslund/vocab/en-us/PlayPlaylist.intent", "name": "mycroft-spotify.forslund:PlayPlaylist.intent"}, "context": null, "type": "padatious:register_intent"}
16:51:27.754 - mycroft.skills.padatious_service:_register_object:89 - DEBUG - Registering Padatious intent: mycroft-spotify.forslund:PlayPlaylist.intent
16:51:27.756 - mycroft.skills.padatious_service:_register_object:89 - DEBUG - Registering Padatious intent: mycroft-spotify.forslund:PlaySong.intent
16:51:28.454 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
16:51:28.455 - SKILLS - DEBUG - {"data": {"event": "mycroft-spotify.forslund:SpotifyLogin"}, "context": null, "type": "mycroft.scheduler.remove_event"}
16:51:28.686 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
16:51:28.695 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
16:51:28.696 - SKILLS - DEBUG - {"data": {"requires": [["mycroft_spotify_forslundSpotify", "mycroft_spotify_forslundSpotify"], ["mycroft_spotify_forslundDevice", "mycroft_spotify_forslundDevice"]], "optional": [], "name": "mycroft-spotify.forslund:list_devices", "at_least_one": []}, "context": null, "type": "register_intent"}
16:51:28.699 - SKILLS - DEBUG - {"data": {"requires": [["mycroft_spotify_forslundPlay", "mycroft_spotify_forslundPlay"], ["mycroft_spotify_forslundSpotify", "mycroft_spotify_forslundSpotify"]], "optional": [], "name": "mycroft-spotify.forslund:play_spotify", "at_least_one": []}, "context": null, "type": "register_intent"}
16:51:29.017 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/playlists?offset=0&limit=50 HTTP/1.1" 200 None
16:51:29.027 - mycroft.skills.core:load_skill:129 - INFO - Loaded mycroft-spotify.forslund
16:51:29.032 - SKILLS - DEBUG - {"data": {"requires": [["mycroft_spotify_forslundTransfer", "mycroft_spotify_forslundTransfer"], ["mycroft_spotify_forslundSpotify", "mycroft_spotify_forslundSpotify"], ["mycroft_spotify_forslundToDevice", "mycroft_spotify_forslundToDevice"]], "optional": [], "name": "mycroft-spotify.forslund:transfer_playback", "at_least_one": []}, "context": null, "type": "register_intent"}
16:51:29.053 - SKILLS - DEBUG - {"data": {"modified": 1526412198.85117, "name": "SpotifySkill", "path": "/opt/mycroft/skills/mycroft-spotify.forslund", "id": "mycroft-spotify.forslund"}, "context": null, "type": "mycroft.skills.loaded"}
16:52:14.049 - SKILLS - DEBUG - {"context": {"ident": "1526482331.89871248774778345797868604", "client_name": "mycroft_listener"}, "data": {"utterances": ["what spotify devices are available"], "session": "c970d1cd-5908-4807-950c-87b2f6c1c45e", "lang": "en-US"}, "type": "recognizer_loop:utterance"}
16:52:14.053 - SKILLS - DEBUG - {"data": {"skill_id": "mycroft-alarm.mycroftai", "utterances": ["what spotify devices are available"], "lang": "en-US"}, "context": null, "type": "skill.converse.request"}
16:52:14.160 - SKILLS - DEBUG - {"data": {"mycroft_spotify_forslundSpotify": "Spotify", "__tags__": [{"start_token": 1, "match": "spotify", "key": "spotify", "entities": [{"data": [["Spotify", "mycroft_spotify_forslundSpotify"]], "confidence": 1.0, "match": "spotify", "key": "spotify"}], "from_context": false, "end_token": 1}, {"start_token": 2, "match": "devices", "key": "devices", "entities": [{"data": [["devices", "mycroft_spotify_forslundDevice"]], "confidence": 1.0, "match": "devices", "key": "devices"}], "from_context": false, "end_token": 2}], "utterance": "what spotify devices are available", "mycroft_spotify_forslundDevice": "devices", "intent_type": "mycroft-spotify.forslund:list_devices", "confidence": 0.6666666666666666, "target": null}, "context": {"client_name": "mycroft_listener", "target": null, "ident": "1526482331.89871248774778345797868604"}, "type": "mycroft-spotify.forslund:list_devices"}
16:52:14.163 - mycroft-spotify_forslund:list_devices:815 - INFO - <mycroft-spotify_forslund.SpotifySkill object at 0x7f616807dda0>
16:52:14.168 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
16:52:14.266 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
16:52:24.271 - SKILLS - DEBUG - {"context": {"ident": "1526482342.18800782757983655706529576", "client_name": "mycroft_listener"}, "data": {"utterances": ["play warming up on spotify"], "session": "c970d1cd-5908-4807-950c-87b2f6c1c45e", "lang": "en-US"}, "type": "recognizer_loop:utterance"}
16:52:24.275 - SKILLS - DEBUG - {"data": {"skill_id": "mycroft-spotify.forslund", "utterances": ["play warming up on spotify"], "lang": "en-US"}, "context": null, "type": "skill.converse.request"}
16:52:24.278 - SKILLS - DEBUG - {"data": {"skill_id": "mycroft-spotify.forslund", "result": false}, "context": null, "type": "skill.converse.response"}
16:52:24.374 - SKILLS - DEBUG - {"data": {"skill_id": "mycroft-alarm.mycroftai", "utterances": ["play warming up on spotify"], "lang": "en-US"}, "context": null, "type": "skill.converse.request"}
16:52:24.479 - SKILLS - DEBUG - {"data": {"mycroft_spotify_forslundSpotify": "on Spotify", "__tags__": [{"start_token": 0, "match": "play", "key": "play", "entities": [{"data": [["play", "mycroft_spotify_forslundPlay"], ["play", "mycroft_npr_news_mycroftaiPlay"], ["play", "mycroft_audio_record_mycroftaiAudioRecordSkillPlayVerb"]], "confidence": 1.0, "match": "play", "key": "play"}], "from_context": false, "end_token": 0}, {"start_token": 3, "match": "on spotify", "key": "on spotify", "confidence": 1.0, "entities": [{"data": [["on Spotify", "mycroft_spotify_forslundSpotify"]], "confidence": 1.0, "match": "on spotify", "key": "on spotify"}], "from_context": false, "end_token": 4}], "utterance": "play warming up on spotify", "intent_type": "mycroft-spotify.forslund:play_spotify", "confidence": 1.0, "target": null, "mycroft_spotify_forslundPlay": "play"}, "context": {"client_name": "mycroft_listener", "target": null, "ident": "1526482342.18800782757983655706529576"}, "type": "mycroft-spotify.forslund:play_spotify"}
16:52:24.482 - SKILLS - DEBUG - {"data": {"name": "SpotifySkill.play_spotify"}, "context": null, "type": "mycroft.skill.handler.start"}
16:52:24.483 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
16:52:24.575 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/currently-playing HTTP/1.1" 204 0
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 625, in play_spotify
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 597, in play_playlist
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 604, in continue_current_playlist
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 464, in get_default_device
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 448, in device_by_name
16:52:24.591 - SKILLS - DEBUG - {"data": {"name": "SpotifySkill.play_spotify"}, "context": null, "type": "mycroft.skill.handler.complete"}
```

**Comment by clebio** [comment]
So, this fails:
```
23:33:43.725 - mycroft.skills.padatious_service:handle_fallback:110 - DEBUG - Padatious fallback attempt: play on ps4
23:33:43.752 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
23:33:43.760 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673622.5331688-1374487465"}, "type": "mycroft-spotify.forslund:PlaySong.intent", "data": {"utterance": "play on ps4", "track": "on ps 4"}}
23:33:43.770 - mycroft-spotify_forslund:play_song:526 - DEBUG - I'm in the play_song handler but I've seen an utterance that contains 'playlist.' I want to play the playlist play. Switching handlers.
23:33:43.779 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673622.5331688-1374487465"}, "type": "mycroft.skill.handler.complete", "data": {"fallback_handler": "PadatiousService.handle_fallback", "handler": "fallback"}}
23:33:43.786 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
23:33:43.816 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673622.5331688-1374487465"}, "type": "mycroft.skill.handler.start", "data": {"name": "SpotifySkill.play_song"}}
23:33:43.955 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/devices HTTP/1.1" 200 None
23:33:43.977 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
23:33:43.986 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/48dcf2cd-df8e-4ace-acd1-d91a7c54cac8/metric/timing HTTP/1.1" 200 280
23:33:44.050 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/48dcf2cd-df8e-4ace-acd1-d91a7c54cac8/metric/timing HTTP/1.1" 200 293
23:33:44.163 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/currently-playing HTTP/1.1" 200 None
23:33:44.183 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
23:33:44.375 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/playlists?limit=50&offset=0 HTTP/1.1" 200 None
23:33:44.403 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Spotify Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 598, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 528, in play_song
    self.play_playlist(message)
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 600, in play_playlist
    self.start_playlist_playback(dev, self.get_best_playlist(playlist))
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 485, in get_best_playlist
    key, confidence = match_one(playlist, self.playlists.keys())
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/util/parse.py", line 56, in match_one
    raise ValueError('a list or dict of choices must be provided')
ValueError: a list or dict of choices must be provided
23:33:44.414 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
```

This also fails:
```
23:34:32.699 - mycroft.skills.padatious_service:handle_fallback:110 - DEBUG - Padatious fallback attempt: play discover weekly
23:34:32.721 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
23:34:32.723 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673671.4869094-1159544329"}, "type": "mycroft.skill.handler.start", "data": {"handler": "fallback"}}
23:34:32.727 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673671.4869094-1159544329"}, "type": "mycroft-spotify.forslund:PlaySong.intent", "data": {"utterance": "play discover weekly", "track": "discover weekly"}}
23:34:32.734 - mycroft-spotify_forslund:play_song:526 - DEBUG - I'm in the play_song handler but I've seen an utterance that contains 'playlist.' I want to play the playlist play. Switching handlers.
23:34:32.748 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.spotify.com
23:34:32.750 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673671.4869094-1159544329"}, "type": "mycroft.skill.handler.complete", "data": {"fallback_handler": "PadatiousService.handle_fallback", "handler": "fallback"}}
23:34:32.786 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "ident": "1528673671.4869094-1159544329"}, "type": "mycroft.skill.handler.start", "data": {"name": "SpotifySkill.play_song"}}
23:34:32.919 - requests.packages.urllib3.connectionpool - DEBUG - https://api.spotify.com:443 "GET /v1/me/player/currently-playing HTTP/1.1" 200 None
23:34:32.947 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Spotify Skill
Traceback (most recent call last):
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/skills/core.py", line 598, in wrapper
    handler(message)
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 528, in play_song
    self.play_playlist(message)
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 600, in play_playlist
    self.start_playlist_playback(dev, self.get_best_playlist(playlist))
  File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 485, in get_best_playlist
    key, confidence = match_one(playlist, self.playlists.keys())
  File "/opt/venvs/mycroft-core/lib/python3.4/site-packages/mycroft/util/parse.py", line 56, in match_one
    raise ValueError('a list or dict of choices must be provided')
ValueError: a list or dict of choices must be provided
23:34:32.964 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
```
This doesn't produce an error, but I don't hear anything playing (what device did it use?):
```
23:35:10.810 - SKILLS - DEBUG - {"type": "recognizer_loop:wakeword", "context": null, "data": {"session": "ee437b64-c3ac-46b0-a6e1-21cb6d575431", "utterance": "mordechai"}}
23:35:11.729 - SKILLS - DEBUG - {"type": "recognizer_loop:utterance", "context": {"ident": "1528673710.78811931683406584", "client_name": "mycroft_listener"}, "data": {"session": "ee437b64-c3ac-46b0-a6e1-21cb6d575431", "utterances": ["next song"], "lang": "en-US"}}
23:35:11.749 - SKILLS - DEBUG - {"context": null, "type": "skill.converse.request", "data": {"lang": "en-US", "utterances": ["next song"], "skill_id": "mycroft-spotify.forslund"}}
23:35:11.769 - SKILLS - DEBUG - {"context": {}, "type": "skill.converse.response", "data": {"result": false, "skill_id": "mycroft-spotify.forslund"}}
23:35:11.845 - mycroft.skills.intent_service:send_metrics:247 - DEBUG - Sending metric if opt_in is enabled
23:35:11.852 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
23:35:11.868 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1528673710.78811931683406584"}, "type": "skill-playback-control:handle_next", "data": {"skill_playback_controlNext": "next", "target": null, "intent_type": "skill-playback-control:handle_next", "skill_playback_controlTrack": "song", "__tags__": [{"entities": [{"data": [["next", "skill_reminderReminderSkillAmount"], ["next", "skill_playback_controlNext"], ["next", "skill_weatherNext"]], "confidence": 1.0, "key": "next", "match": "next"}], "key": "next", "end_token": 0, "start_token": 0, "match": "next", "from_context": false}, {"entities": [{"data": [["song", "skill_playback_controlTrack"]], "confidence": 1.0, "key": "song", "match": "song"}], "key": "song", "end_token": 1, "start_token": 1, "match": "song", "from_context": false}], "utterance": "next song", "confidence": 1.0}}
23:35:11.888 - requests.packages.urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.mycroft.ai
23:35:11.891 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1528673710.78811931683406584"}, "type": "mycroft.skill.handler.start", "data": {"name": "Playback Control Skill.handle_next"}}
23:35:11.935 - SKILLS - DEBUG - {"context": null, "type": "mycroft.audio.service.next", "data": {}}
23:35:11.938 - SKILLS - DEBUG - {"context": {"client_name": "mycroft_listener", "target": null, "ident": "1528673710.78811931683406584"}, "type": "mycroft.skill.handler.complete", "data": {"name": "Playback Control Skill.handle_next"}}
23:35:12.125 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/48dcf2cd-df8e-4ace-acd1-d91a7c54cac8/metric/timing HTTP/1.1" 200 298
23:35:12.141 - requests.packages.urllib3.connectionpool - DEBUG - https://api.mycroft.ai:443 "POST /v1/device/48dcf2cd-df8e-4ace-acd1-d91a7c54cac8/metric/timing HTTP/1.1" 200 272
23:35:20.448 - SKILLS - DEBUG - {"context": null, "type": "skill-date-time:TimeSkillupdate_display", "data": {}}
```

**Comment by clebio** [comment]
Sorrry, I'm on picroft (with AIY fwiw):

```
pi@picroft:~ $ cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
...```

**Comment by forslund** [comment]
Thanks @clebio, I believe the playlist issue is fixed and will be in this weeks release the release I'm working on.

**Comment by forslund** [comment]
This has been resolved in the latest release of the skill. Closing
