### ISSUE TITLE
Error during command "play metal": "An error occurred while processing a request in Spotify Skill"

### ISSUE THREAD

**Issue by M-arcus** [forslund/spotify-skill#40]
```21:42:34.036 - __main__:handle_utterance:61 - INFO - Utterance: ['list spotify devices']
21:42:42.857 - __main__:handle_record_begin:35 - INFO - Begin Recording...
21:42:48.051 - __main__:handle_record_end:40 - INFO - End Recording...
21:42:48.055 - __main__:handle_wakeword:56 - INFO - Wakeword Detected: hey mycroft
21:42:50.326 - __main__:handle_utterance:61 - INFO - Utterance: ['play metal']
21:42:50.974 - mycroft.skills.core:wrapper:607 - ERROR - An error occurred while processing a request in Spotify Skill
Traceback (most recent call last):
File "/home/user/Projects/mycroft-core/mycroft/skills/core.py", line 598, in wrapper
handler(message)
File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 528, in play_song
self.play_playlist(message)
File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 600, in play_playlist
self.start_playlist_playback(dev, self.get_best_playlist(playlist))
File "/opt/mycroft/skills/mycroft-spotify.forslund/__init__.py", line 485, in get_best_playlist
key, confidence = match_one(playlist, self.playlists.keys())
File "/home/user/Projects/mycroft-core/mycroft/util/parse.py", line 56, in match_one
raise ValueError('a list or dict of choices must be provided')
ValueError: a list or dict of choices must be provided
```

**Comment by M-arcus** [comment]
Also happens with `play next`

**Comment by dmwilsonkc** [comment]
I am also getting the same error:

`~~~~:607 - ERROR - An error occurred while processing a request in Spotify Skill
Traceback (most recent call last):
File "/home/pi/mycroft-core/mycroft/skills/core.py", line 598, in wrapper
handler(message)
File "/opt/mycroft/skills/spotify-skill/__init__.py", line 528, in play_song
self.play_playlist(message)
File "/opt/mycroft/skills/spotify-skill/__init__.py", line 600, in play_playlist
self.start_playlist_playback(dev, self.get_best_playlist(playlist))
~~~~pt/mycroft/skills/spotify-skill/__init__.py", line 485, in get_best_playlist
key, confidence = match_one(playlist, self.playlists.keys())
File "/home/pi/mycroft-core/mycroft/util/parse.py", line 56, in match_one
raise ValueError('a list or dict of choices must be provided')
ValueError: a list or dict of choices must be provided
`

**Comment by forslund** [comment]
No worries.

Feel free to check out the branch [bugfix/playlists](https://github.com/forslund/spotify-skill/tree/bugfix/playlists)

Should at least be an improvement at this point.

**Comment by M-arcus** [comment]
@forslund Thank you, it works better now.

The song choices are quite odd, depending on the transcribed requests. Especially ones with shorter titles.

It also tries to select albums now, instead of specific songs.

**Comment by forslund** [comment]
I think this is intended functionallity

User says *play X*

1. spotify skill checks if there's a playlist matching X
2. spotify skill checks if there's an album matching X

To play a single track ask it to *play the song X by Y*

**Comment by forslund** [comment]
Can you give examples of shorter titles that gives weird results?
